// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Yhes_GMb0GwzhFcb7R7-9oJvsOgS75Q',
    appId: '1:455805989708:web:97091ea82a4743775315e9',
    messagingSenderId: '455805989708',
    projectId: 'fir-chat-9c443',
    authDomain: 'fir-chat-9c443.firebaseapp.com',
    storageBucket: 'fir-chat-9c443.appspot.com',
    measurementId: 'G-78ET1HT906',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX-l9ex-FWG-7PNL0T2rjGExYyvwA9BDw',
    appId: '1:455805989708:android:6f2774ae34d682ab5315e9',
    messagingSenderId: '455805989708',
    projectId: 'fir-chat-9c443',
    storageBucket: 'fir-chat-9c443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3NdP2L1gRKk1GFec0ldra2fxHQIl-zsU',
    appId: '1:455805989708:ios:9eb6ea515a6f95175315e9',
    messagingSenderId: '455805989708',
    projectId: 'fir-chat-9c443',
    storageBucket: 'fir-chat-9c443.appspot.com',
    iosBundleId: 'com.example.demoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3NdP2L1gRKk1GFec0ldra2fxHQIl-zsU',
    appId: '1:455805989708:ios:9eb6ea515a6f95175315e9',
    messagingSenderId: '455805989708',
    projectId: 'fir-chat-9c443',
    storageBucket: 'fir-chat-9c443.appspot.com',
    iosBundleId: 'com.example.demoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Yhes_GMb0GwzhFcb7R7-9oJvsOgS75Q',
    appId: '1:455805989708:web:5db39ee36bd5b43c5315e9',
    messagingSenderId: '455805989708',
    projectId: 'fir-chat-9c443',
    authDomain: 'fir-chat-9c443.firebaseapp.com',
    storageBucket: 'fir-chat-9c443.appspot.com',
    measurementId: 'G-D28DFYK7YT',
  );
}
